project:
  type: website


format:
  html:
    theme: cosmo
    css:
      - stylesheets/code_select.css
      - stylesheets/extra.css

    toc: true


metadata-files:
  - reference/_sidebar.yml


website:
  title: "Ibis Project"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: concept/why_ibis.md
        text: Concepts
      - href: tutorial/index.md
        text: Tutorials
      - href: how_to/configuration.md
        text: How-to guides
      - href: reference/index.qmd
      - href: blog/rendered/ibis-version-6.0.0-release.ipynb
        text: Blog
      - href: community/index.md
        text: Community
      - href: release_notes.md
        text: "🚧 Release notes"

  sidebar:
    - id: blog
      title: Blog
      contents: 
        - blog/rendered/ibis-version-6.0.0-release.ipynb
        - blog/rendered/torch.ipynb
        - blog/rendered/campaign-finance.ipynb
        - blog/ibis-to-file.md
        - blog/ibis-examples.md
        - blog/selectors.md
        - blog/ibis_substrait_to_duckdb.md
        - blog/ibis-version-4.0.0-release.md
        - blog/rendered/ci-analysis.ipynb
        - blog/ffill-and-bfill-using-ibis.md
        - blog/Ibis-version-3.1.0-release.md
        - blog/Ibis-version-3.0.0-release.md
    - id: concept
      title: Concepts
      contents:
        - concept/why_ibis.md
        - concept/design.md
        - concept/backends.md
    - id: tutorial
      title: Tutorials
      contents: 
        - tutorial/index.md
        # TODO: note that two tutorials need titles
        # they show up as "install" as a result
        - auto: tutorial/*
    - id: how-to
      title: How-to guides
      contents:
        - configuration.md
        - chain_expressions.md
        - ffill_bfill_w_window.md
        - self_joins.md
        - sessionize.md
        - topk.md
        - memtable_join.md
        - duckdb_register.md
        - streamlit.md
        - section: Extend with custom operations
          contents:
            - how_to/extending/elementwise.ipynb
            - how_to/extending/reduction.ipynb
            


quartodoc:
  package: ibis
  title: Reference
  sidebar: reference/_sidebar.yml
  sections:
    - title: Expressions
      desc: ""
      package: ibis.expr.types
      contents:
        - kind: page
          package: ibis
          path: top_level
          summary:
            name: Top-level APIs
            desc: These methods and objecst are available directly on the `ibis` module.
          contents:
            - name: and_
              dynamic: true

        - kind: page
          path: expression-tables
          package: ibis.expr.types.relations
          summary:
            name: Table Expressions
            desc: Table expressions form the basis for most Ibis expressions.
          contents:
            - Table
            - GroupedTable

        - kind: page
          path: expression-generic
          package: ibis.expr.types.generic
          summary:
            name: Generic Expression APIs
            desc: These expressions are available on scalars and columns of any element type.
          contents:
            - Value
            - Column
            - Scalar

        - kind: page
          path: expression-numeric
          package: ibis.expr.types.numeric
          summary:
            name: Numeric and Boolean Expressions
            desc: These APIs are available on numeric and boolean expressions.
          contents:
            - NumericValue
            - NumericColumn
            - IntegerValue
            - IntegerColumn
            - FloatingValue
            - DecimalValue
            - name: BooleanValue
              package: ibis.expr.types.logical

        - kind: page
          path: expression-strings
          package: ibis.expr.types.strings
          summary:
            name: String Expressions
            desc: All string operations are valid for both scalars and columns.
          contents:
            - StringValue
        - temporal


        - kind: page
          path: expression-collections
          summary:
            name: Complex Type Expressions
            desc: These APIs are available on arrays, maps and structs.
          contents:
            - name: ArrayValue
              package: ibis.expr.types.arrays
            - name: StructValue
              package: ibis.expr.types.structs
            - name: MapValue
              package: ibis.expr.types.maps


        - kind: page
          path: expression-geospatial
          package: ibis.expr.types.geospatial
          summary:
            name: Geospatial Expressions
            desc: Ibis supports the following geospatial expression APIs
          contents:
            - GeoSpatialValue
            - GeoSpatialColumn
    - title: Other
      desc: ""
      package: ibis
      contents:
        # # Column Selectors
        - selectors

        # # Schemas
        # 
        # This module contains APIs for interacting with table schemas.
        - expr.schema.Schema

        # # Configuration Options
        - config.Options
        - config.Repr
        - config.SQL
        - config.ContextAdjustment
        
        # # Data Types
        # 
        # This module contains classes for handling the different logical types that
        # occur in databases.
        #
        # All data type constructors take a `nullable: bool` parameter whose default
        # value is [`True`][True].
        - expr.datatypes.core
